# Generated by Django 6.0.3 on 2026-04-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('DELUXE', 'Deluxe'), ('SUITE', 'Suite')], max_length=100)),
                ('room_image', models.ImageField(upload_to='room_images/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='assigned_room',
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='room',
        ),
        migrations.AlterField(
            model_name='hotelgallery',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
